package com.ollite.llm.server.ui.server

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.ContentCopy
import androidx.compose.material.icons.outlined.Refresh
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.ollite.llm.server.ui.navigation.ServerStatus
import com.ollite.llm.server.ui.navigation.StatusPill
import com.ollite.llm.server.ui.theme.OlliteGreen400
import com.ollite.llm.server.ui.theme.OllitePrimary
import com.ollite.llm.server.ui.theme.SpaceGroteskFontFamily
import kotlinx.coroutines.delay

@Composable
fun StatusScreen(
  serverViewModel: ServerViewModel,
  onReloadModel: () -> Unit,
  modifier: Modifier = Modifier,
) {
  val status by serverViewModel.status.collectAsState()
  val modelName by serverViewModel.activeModelName.collectAsState()
  val port by serverViewModel.port.collectAsState()
  val bindAddress by serverViewModel.bindAddress.collectAsState()
  val startedAtMs by serverViewModel.startedAtMs.collectAsState()
  val requestCount by serverViewModel.requestCount.collectAsState()
  val tokensGenerated by serverViewModel.tokensGenerated.collectAsState()
  val lastLatencyMs by serverViewModel.lastLatencyMs.collectAsState()
  val avgLatencyMs by serverViewModel.avgLatencyMs.collectAsState()

  if (status == ServerStatus.STOPPED) {
    EmptyStatusScreen(modifier)
    return
  }

  // Live uptime ticker
  var uptimeSeconds by remember { mutableLongStateOf(0L) }
  LaunchedEffect(startedAtMs, status) {
    if (status == ServerStatus.RUNNING && startedAtMs > 0) {
      while (true) {
        uptimeSeconds = (System.currentTimeMillis() - startedAtMs) / 1000
        delay(1000)
      }
    } else {
      uptimeSeconds = 0L
    }
  }

  val endpointUrl = "http://${bindAddress ?: "localhost"}:$port/v1"

  // Throughput: tokens/sec based on uptime
  val throughput = if (uptimeSeconds > 0) {
    "%.1f".format(tokensGenerated.toDouble() / uptimeSeconds)
  } else {
    "0.0"
  }

  Column(
    modifier = modifier
      .fillMaxSize()
      .verticalScroll(rememberScrollState())
      .padding(horizontal = 20.dp, vertical = 16.dp),
    verticalArrangement = Arrangement.spacedBy(16.dp),
  ) {
    // Status pill centered
    Box(modifier = Modifier.fillMaxWidth(), contentAlignment = Alignment.Center) {
      StatusPill(serverStatus = status)
    }

    // Model info card
    StatusCard {
      Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
      ) {
        Column(modifier = Modifier.weight(1f)) {
          Text(
            text = "Active Model",
            style = MaterialTheme.typography.labelMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
          )
          Spacer(modifier = Modifier.height(4.dp))
          Text(
            text = modelName ?: "Loading…",
            style = MaterialTheme.typography.titleMedium,
            color = MaterialTheme.colorScheme.onSurface,
          )
        }
        IconButton(onClick = onReloadModel) {
          Icon(
            imageVector = Icons.Outlined.Refresh,
            contentDescription = "Reload model",
            tint = OllitePrimary,
          )
        }
      }
    }

    // Endpoint card
    val context = LocalContext.current
    StatusCard {
      Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
      ) {
        Column(modifier = Modifier.weight(1f)) {
          Text(
            text = "Endpoint",
            style = MaterialTheme.typography.labelMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
          )
          Spacer(modifier = Modifier.height(4.dp))
          Text(
            text = endpointUrl,
            style = MaterialTheme.typography.bodyMedium,
            color = OllitePrimary,
            fontFamily = SpaceGroteskFontFamily,
          )
        }
        IconButton(onClick = { copyToClipboard(context, endpointUrl) }) {
          Icon(
            imageVector = Icons.Outlined.ContentCopy,
            contentDescription = "Copy endpoint URL",
            tint = OllitePrimary,
          )
        }
      }
    }

    // Metrics grid 2x3
    Text(
      text = "Metrics",
      style = MaterialTheme.typography.titleSmall,
      color = MaterialTheme.colorScheme.onSurfaceVariant,
      modifier = Modifier.padding(top = 4.dp),
    )

    Row(
      modifier = Modifier.fillMaxWidth(),
      horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
      MetricCard(
        label = "Uptime",
        value = formatUptime(uptimeSeconds),
        modifier = Modifier.weight(1f),
      )
      MetricCard(
        label = "Requests",
        value = requestCount.toString(),
        modifier = Modifier.weight(1f),
      )
    }

    Row(
      modifier = Modifier.fillMaxWidth(),
      horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
      MetricCard(
        label = "Last Latency",
        value = if (lastLatencyMs > 0) "${lastLatencyMs}ms" else "—",
        modifier = Modifier.weight(1f),
      )
      MetricCard(
        label = "Tokens Out",
        value = tokensGenerated.toString(),
        modifier = Modifier.weight(1f),
      )
    }

    Row(
      modifier = Modifier.fillMaxWidth(),
      horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
      MetricCard(
        label = "Avg Latency",
        value = if (avgLatencyMs > 0) "${avgLatencyMs}ms" else "—",
        modifier = Modifier.weight(1f),
      )
      MetricCard(
        label = "Throughput",
        value = "${throughput} t/s",
        modifier = Modifier.weight(1f),
      )
    }
  }
}

@Composable
private fun EmptyStatusScreen(modifier: Modifier = Modifier) {
  Box(
    modifier = modifier.fillMaxSize(),
    contentAlignment = Alignment.Center,
  ) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
      Text(
        text = "No active server",
        style = MaterialTheme.typography.titleMedium,
        color = MaterialTheme.colorScheme.onSurface,
      )
      Spacer(modifier = Modifier.height(8.dp))
      Text(
        text = "Start a model from the Models tab.",
        style = MaterialTheme.typography.bodyMedium,
        color = MaterialTheme.colorScheme.onSurfaceVariant,
      )
    }
  }
}

@Composable
private fun StatusCard(
  modifier: Modifier = Modifier,
  content: @Composable () -> Unit,
) {
  Box(
    modifier = modifier
      .fillMaxWidth()
      .clip(RoundedCornerShape(24.dp))
      .background(MaterialTheme.colorScheme.surfaceContainerLow)
      .padding(20.dp),
  ) {
    content()
  }
}

@Composable
private fun MetricCard(
  label: String,
  value: String,
  modifier: Modifier = Modifier,
) {
  Column(
    modifier = modifier
      .clip(RoundedCornerShape(20.dp))
      .background(MaterialTheme.colorScheme.surfaceContainerLow)
      .padding(16.dp),
  ) {
    Text(
      text = value,
      style = MaterialTheme.typography.headlineSmall,
      color = MaterialTheme.colorScheme.onSurface,
      fontWeight = FontWeight.Bold,
    )
    Spacer(modifier = Modifier.height(4.dp))
    Text(
      text = label,
      style = MaterialTheme.typography.labelSmall,
      color = MaterialTheme.colorScheme.onSurfaceVariant,
    )
  }
}

private fun formatUptime(totalSeconds: Long): String {
  val hours = totalSeconds / 3600
  val minutes = (totalSeconds % 3600) / 60
  val seconds = totalSeconds % 60
  return "%02d:%02d:%02d".format(hours, minutes, seconds)
}

private fun copyToClipboard(context: Context, text: String) {
  val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
  clipboard.setPrimaryClip(ClipData.newPlainText("Ollite Endpoint", text))
  Toast.makeText(context, "Copied to clipboard", Toast.LENGTH_SHORT).show()
}
