package com.ollitert.llm.server.ui.server

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.ContentCopy
import androidx.compose.material.icons.outlined.Refresh
import androidx.compose.foundation.clickable
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.ollitert.llm.server.ui.navigation.ServerStatus
import com.ollitert.llm.server.ui.theme.OlliteRTGreen400
import com.ollitert.llm.server.ui.theme.OlliteRTPrimary
import com.ollitert.llm.server.ui.theme.SpaceGroteskFontFamily
import kotlinx.coroutines.delay

@Composable
fun StatusScreen(
  serverViewModel: ServerViewModel,
  onReloadModel: () -> Unit,
  modifier: Modifier = Modifier,
) {
  val status by serverViewModel.status.collectAsState()
  val modelName by serverViewModel.activeModelName.collectAsState()
  val port by serverViewModel.port.collectAsState()
  val bindAddress by serverViewModel.bindAddress.collectAsState()
  val startedAtMs by serverViewModel.startedAtMs.collectAsState()
  val requestCount by serverViewModel.requestCount.collectAsState()
  val tokensGenerated by serverViewModel.tokensGenerated.collectAsState()
  val tokensIn by serverViewModel.tokensIn.collectAsState()
  val lastLatencyMs by serverViewModel.lastLatencyMs.collectAsState()
  val peakLatencyMs by serverViewModel.peakLatencyMs.collectAsState()
  val avgLatencyMs by serverViewModel.avgLatencyMs.collectAsState()
  val textRequests by serverViewModel.textRequests.collectAsState()
  val imageRequests by serverViewModel.imageRequests.collectAsState()
  val audioRequests by serverViewModel.audioRequests.collectAsState()
  val errorCount by serverViewModel.errorCount.collectAsState()
  val modelLoadTimeMs by serverViewModel.modelLoadTimeMs.collectAsState()
  val loadingStartedAtMs by serverViewModel.loadingStartedAtMs.collectAsState()
  val lastError by serverViewModel.lastError.collectAsState()

  val isStopped = status == ServerStatus.STOPPED
  val isLoading = status == ServerStatus.LOADING

  // Live uptime ticker
  var uptimeSeconds by remember { mutableLongStateOf(0L) }
  LaunchedEffect(startedAtMs, status) {
    if (status == ServerStatus.RUNNING && startedAtMs > 0) {
      while (true) {
        uptimeSeconds = (System.currentTimeMillis() - startedAtMs) / 1000
        delay(1000)
      }
    } else {
      uptimeSeconds = 0L
    }
  }

  // Loading elapsed timer — driven by loadingStartedAtMs from ServerMetrics,
  // so it persists across screen navigation and starts when the model begins loading.
  var loadingElapsedSeconds by remember { mutableLongStateOf(0L) }
  LaunchedEffect(loadingStartedAtMs) {
    if (loadingStartedAtMs > 0) {
      while (true) {
        loadingElapsedSeconds = (System.currentTimeMillis() - loadingStartedAtMs) / 1000
        delay(1000)
      }
    } else {
      loadingElapsedSeconds = 0L
    }
  }

  val endpointUrl = "http://${bindAddress ?: "localhost"}:$port/v1"

  // Throughput: tokens/sec based on uptime
  val throughput = if (uptimeSeconds > 0) {
    "%.1f".format(tokensGenerated.toDouble() / uptimeSeconds)
  } else {
    "0.0"
  }

  Column(
    modifier = modifier
      .fillMaxSize()
      .verticalScroll(rememberScrollState())
      .padding(horizontal = 20.dp, vertical = 16.dp),
    verticalArrangement = Arrangement.spacedBy(16.dp),
  ) {
    // Server not running banner
    if (isStopped) {
      Box(
        modifier = Modifier
          .fillMaxWidth()
          .clip(RoundedCornerShape(16.dp))
          .background(MaterialTheme.colorScheme.errorContainer.copy(alpha = 0.3f))
          .padding(16.dp),
        contentAlignment = Alignment.Center,
      ) {
        Column(horizontalAlignment = Alignment.CenterHorizontally) {
          Text(
            text = "Server not running",
            style = MaterialTheme.typography.titleMedium,
            color = MaterialTheme.colorScheme.onSurface,
            fontWeight = FontWeight.SemiBold,
          )
          Spacer(modifier = Modifier.height(4.dp))
          Text(
            text = "Start a model from the Models tab to begin serving requests.",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
          )
        }
      }
    }

    // Model info card
    StatusCard {
      Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
      ) {
        Column(modifier = Modifier.weight(1f)) {
          Text(
            text = "Active Model",
            style = MaterialTheme.typography.labelMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
          )
          Spacer(modifier = Modifier.height(4.dp))
          Text(
            text = if (isStopped) "None" else (modelName ?: "Loading…"),
            style = MaterialTheme.typography.titleMedium,
            color = if (isStopped) MaterialTheme.colorScheme.onSurfaceVariant else MaterialTheme.colorScheme.onSurface,
          )
          if (status == ServerStatus.ERROR) {
            Spacer(modifier = Modifier.height(2.dp))
            val errorText = if (!lastError.isNullOrBlank()) {
              if (lastError!!.length > 80) "Failed to load — check Logs for details"
              else "Failed: $lastError"
            } else {
              "Failed to load model"
            }
            Text(
              text = errorText,
              style = MaterialTheme.typography.labelSmall,
              color = MaterialTheme.colorScheme.error,
              maxLines = 2,
            )
          } else if (isLoading) {
            Spacer(modifier = Modifier.height(2.dp))
            Text(
              text = "Loading… ${loadingElapsedSeconds}s",
              style = MaterialTheme.typography.labelSmall,
              color = OlliteRTPrimary.copy(alpha = 0.7f),
            )
          } else if (!isStopped && modelLoadTimeMs > 0) {
            Spacer(modifier = Modifier.height(2.dp))
            Text(
              text = "Loaded in ${formatLoadTime(modelLoadTimeMs)}",
              style = MaterialTheme.typography.labelSmall,
              color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.7f),
            )
          }
        }
        if (!isStopped) {
          if (isLoading) {
            Box(
              modifier = Modifier
                .size(40.dp)
                .clip(RoundedCornerShape(10.dp))
                .background(MaterialTheme.colorScheme.surfaceContainerHighest),
              contentAlignment = Alignment.Center,
            ) {
              CircularProgressIndicator(
                modifier = Modifier.size(22.dp),
                color = OlliteRTPrimary,
                strokeWidth = 2.dp,
              )
            }
          } else {
            Box(
              modifier = Modifier
                .size(40.dp)
                .clip(RoundedCornerShape(10.dp))
                .background(MaterialTheme.colorScheme.surfaceContainerHighest)
                .clickable { onReloadModel() },
              contentAlignment = Alignment.Center,
            ) {
              Icon(
                imageVector = Icons.Outlined.Refresh,
                contentDescription = "Reload model",
                tint = OlliteRTPrimary,
                modifier = Modifier.size(22.dp),
              )
            }
          }
        }
      }
    }

    // Endpoint card
    val context = LocalContext.current
    val uriHandler = LocalUriHandler.current
    StatusCard {
      Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
      ) {
        Column(modifier = Modifier.weight(1f)) {
          Text(
            text = "Endpoint",
            style = MaterialTheme.typography.labelMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
          )
          Spacer(modifier = Modifier.height(4.dp))
          Text(
            text = if (isStopped) "—" else endpointUrl,
            style = MaterialTheme.typography.bodyMedium,
            color = if (isStopped) MaterialTheme.colorScheme.onSurfaceVariant else OlliteRTPrimary,
            fontFamily = SpaceGroteskFontFamily,
            textDecoration = if (isStopped) TextDecoration.None else TextDecoration.Underline,
            modifier = if (!isStopped) Modifier.clickable { uriHandler.openUri(endpointUrl) } else Modifier,
          )
        }
        if (!isStopped) {
          Box(
            modifier = Modifier
              .size(40.dp)
              .clip(RoundedCornerShape(10.dp))
              .background(MaterialTheme.colorScheme.surfaceContainerHighest)
              .clickable { copyToClipboard(context, endpointUrl) },
            contentAlignment = Alignment.Center,
          ) {
            Icon(
              imageVector = Icons.Outlined.ContentCopy,
              contentDescription = "Copy endpoint URL",
              tint = OlliteRTPrimary,
              modifier = Modifier.size(22.dp),
            )
          }
        }
      }
    }

    // Metrics grid
    Text(
      text = "Metrics",
      style = MaterialTheme.typography.titleSmall,
      color = MaterialTheme.colorScheme.onSurfaceVariant,
      modifier = Modifier.padding(top = 4.dp),
    )

    Row(
      modifier = Modifier.fillMaxWidth(),
      horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
      MetricCard(
        label = "Uptime",
        value = formatUptime(uptimeSeconds),
        modifier = Modifier.weight(1f),
      )
      MetricCard(
        label = "Requests",
        value = requestCount.toString(),
        modifier = Modifier.weight(1f),
      )
    }

    Row(
      modifier = Modifier.fillMaxWidth(),
      horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
      MetricCard(
        label = "Tokens In",
        value = tokensIn.toString(),
        modifier = Modifier.weight(1f),
      )
      MetricCard(
        label = "Tokens Out",
        value = tokensGenerated.toString(),
        modifier = Modifier.weight(1f),
      )
    }

    Row(
      modifier = Modifier.fillMaxWidth(),
      horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
      MetricCard(
        label = "Throughput",
        value = "${throughput} t/s",
        modifier = Modifier.weight(1f),
      )
      MetricCard(
        label = "Tokens / Request",
        value = if (requestCount > 0) "%.1f".format(tokensGenerated.toDouble() / requestCount) else "—",
        modifier = Modifier.weight(1f),
      )
    }

    Row(
      modifier = Modifier.fillMaxWidth(),
      horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
      MetricCard(
        label = "Last Latency",
        value = if (lastLatencyMs > 0) "${lastLatencyMs}ms" else "—",
        modifier = Modifier.weight(1f),
      )
      MetricCard(
        label = "Avg Latency",
        value = if (avgLatencyMs > 0) "${avgLatencyMs}ms" else "—",
        modifier = Modifier.weight(1f),
      )
    }

    Row(
      modifier = Modifier.fillMaxWidth(),
      horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
      MetricCard(
        label = "Peak Latency",
        value = if (peakLatencyMs > 0) "${peakLatencyMs}ms" else "—",
        modifier = Modifier.weight(1f),
      )
      val successRate = if (requestCount > 0) {
        "%.0f%%".format(((requestCount - errorCount).toDouble() / requestCount) * 100)
      } else "—"
      MetricCard(
        label = "Success Rate",
        value = if (requestCount > 0) "$successRate (${errorCount} err)" else "—",
        modifier = Modifier.weight(1f),
      )
    }

    // Request modality breakdown
    if (requestCount > 0) {
      Text(
        text = "Request Types",
        style = MaterialTheme.typography.titleSmall,
        color = MaterialTheme.colorScheme.onSurfaceVariant,
        modifier = Modifier.padding(top = 4.dp),
      )

      Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.spacedBy(12.dp),
      ) {
        MetricCard(
          label = "Text",
          value = textRequests.toString(),
          modifier = Modifier.weight(1f),
        )
        MetricCard(
          label = "Vision",
          value = imageRequests.toString(),
          modifier = Modifier.weight(1f),
        )
        MetricCard(
          label = "Audio",
          value = audioRequests.toString(),
          modifier = Modifier.weight(1f),
        )
      }
    }
  }
}

@Composable
private fun LoadingStatusScreen(modelName: String?, modifier: Modifier = Modifier) {
  Box(
    modifier = modifier.fillMaxSize(),
    contentAlignment = Alignment.Center,
  ) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
      CircularProgressIndicator(
        modifier = Modifier.size(48.dp),
        color = OlliteRTPrimary,
        strokeWidth = 4.dp,
      )
      Spacer(modifier = Modifier.height(16.dp))
      Text(
        text = "Loading model…",
        style = MaterialTheme.typography.titleMedium,
        color = MaterialTheme.colorScheme.onSurface,
      )
      if (modelName != null) {
        Spacer(modifier = Modifier.height(4.dp))
        Text(
          text = modelName,
          style = MaterialTheme.typography.bodyMedium,
          color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
      }
    }
  }
}

@Composable
private fun StatusCard(
  modifier: Modifier = Modifier,
  content: @Composable () -> Unit,
) {
  Box(
    modifier = modifier
      .fillMaxWidth()
      .clip(RoundedCornerShape(24.dp))
      .background(MaterialTheme.colorScheme.surfaceContainerLow)
      .padding(20.dp),
  ) {
    content()
  }
}

@Composable
private fun MetricCard(
  label: String,
  value: String,
  modifier: Modifier = Modifier,
) {
  Column(
    modifier = modifier
      .clip(RoundedCornerShape(20.dp))
      .background(MaterialTheme.colorScheme.surfaceContainerLow)
      .padding(16.dp),
  ) {
    Text(
      text = value,
      style = MaterialTheme.typography.headlineSmall,
      color = MaterialTheme.colorScheme.onSurface,
      fontWeight = FontWeight.Bold,
    )
    Spacer(modifier = Modifier.height(4.dp))
    Text(
      text = label,
      style = MaterialTheme.typography.labelSmall,
      color = MaterialTheme.colorScheme.onSurfaceVariant,
    )
  }
}

private fun formatLoadTime(ms: Long): String {
  return when {
    ms < 1000 -> "${ms}ms"
    ms < 60_000 -> "%.1fs".format(ms / 1000.0)
    else -> "%dm %ds".format(ms / 60_000, (ms % 60_000) / 1000)
  }
}

private fun formatUptime(totalSeconds: Long): String {
  val hours = totalSeconds / 3600
  val minutes = (totalSeconds % 3600) / 60
  val seconds = totalSeconds % 60
  return "%02d:%02d:%02d".format(hours, minutes, seconds)
}

private fun copyToClipboard(context: Context, text: String) {
  val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
  clipboard.setPrimaryClip(ClipData.newPlainText("OlliteRT Endpoint", text))
  Toast.makeText(context, "Copied to clipboard", Toast.LENGTH_SHORT).show()
}
